version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    command: air

  structure:
    build: 
      dockerfile: Dockerfile.gocallvis
    ports:
      - "7878:7878"
    volumes:
      - .:/usr/app
    command: go-callvis -ignore hoge/pkg,github.com/gin-gonic/gin cmd/main.go
