name: reviewdog
on: [push]
jobs:
  reviewdog:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create testing image
        run: make install

      - name: Calculare coupling
        run: make metrics

      - name: create folder
        run: mkdir coverage

      - name: Unit test
        run: make test-coverage

      - name: architecture compliance
        run: make arch

      - name: Report
        run: make report

      - name: github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./spm-go
          keep_files: true
          enable_jekyll: true

      - name: github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./.arch-go
          keep_files: true
          enable_jekyll: true

      - name: github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: .report.html
          keep_files: true
          enable_jekyll: true

      - name: github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./coverage/coverage.html
          keep_files: true
          enable_jekyll: true

      
