name: reviewdog
on: [push]
jobs:
  reviewdog:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: nightly
      - run: reviewdog -version 

      - name: Create testing image
        run: make install

      - name: complexity analysis
        uses: shoooooman/go-complexity-analysis-action@v1
        with:
          github_token: ${{ secrets.TOKEN }}
          cycloover: 5
          maintunder: 30

      - name: Calculare coupling
        run: |
          make coupling

      - name: architecture compliance
        run: |
          make arch

      - name: Deploy coupling
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./spm-go
          keep_files: true
          enable_jekyll: true

      - name: Deploy architecture
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./.arch-go
          keep_files: true
          enable_jekyll: true

      # - name: Run reviewdog
      #   env:
      #     REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.TOKEN }}
      #   run: |
      #     reviewdog -reporter=github-check
