name: reviewdog
on: [push]
jobs:
  reviewdog:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Setup reviewdog
        run: |
          mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $HOME/bin
          echo ::add-path::$HOME/bin
      
      - name: Install Golang
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      
      - name: Install golanglint-ci
        run: |
          git clone https://github.com/golangci/golangci-lint.git
          cd golang golangci-lint/
          CGO_ENABLED=1 make build 
          mv golangci-lint $HOME/bin
          golanglint run 
