name: reviewdog
on: [push]
jobs:
  reviewdog:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: nightly
      - run: reviewdog -version
      
      - name: Install Golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: GolangLint-CI
        run: |
          git clone https://github.com/golangci/golangci-lint.git
          cd golangci-lint/
          CGO_ENABLED=1 make build 
          mv golangci-lint $HOME/.local/bin
          golangci-lint run 
