name: reviewdog
on: [push]
jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest # Optional. [latest,nightly,v.X.Y.Z]
      # - name: Run reviewdog
      #   env:
      #     github_token: ${{ secrets.TOKEN }}
      #   run: |
      #     reviewdog -reporter=github-check -runners=govet

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.TOKEN }}
          reviewdog_flags: "-reporter=github-check"
          golangci_lint_flags: "--exclude-use-default=false"