name: reviewdog
on: [push]
jobs:
  reviewdog:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: nightly
      - run: reviewdog -version 

      - name: Create testing image
        run: make install

      - name: linter
        run: make linter

      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.TOKEN }}
        run: |
          reviewdog -reporter=github-check
